function plot_spread(X1, Y1, title_plot, corr, cc, cont_A, cont_B)
%plot_spread(X1, Y1, corr, cc, deposit, cont_A, cont_B)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 02-Nov-2013 19:18:38

% Create figure
figure1 = figure;

% Create axes
% axes1 = axes('Parent',figure1,'YGrid','on',...
%     'Position',[0.13 0.11 0.774999999999999 0.777382690302398]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1 132]);
%% Uncomment the following line to preserve the Y-limits of the axes

box on;
hold on;

% Create xlabel
xlabel('Date','FontWeight','bold','FontSize',16);

% Create ylabel
ylabel('Residual','FontWeight','bold','FontSize',16);

% Create title
title(title_plot,'FontSize',24,'FontName','Impact',...
    'Color',[0.0784313753247261 0.168627455830574 0.549019634723663]);

% Create plot
plot(X1, Y1,'LineWidth',1,...
    'Color',[0.0392156876623631 0.141176477074623 0.415686279535294]);

% Create textbox
tmp_str = sprintf('correlation : %3.1f%%     cointegration : %10.3f       contraction A : %d     contraction B : %d', corr, cc, cont_A, cont_B);
%tmp_str = sprintf('correlation      : %3.1f%%\ncointegration  : %10.3f\ntotal deposit   : %d\ncontraction A :  %d\ncontraction B :  %d', corr, cc, deposit, cont_A, cont_B);
% tmp_str = sprintf('correlation : %3.1f' ,'cointegration : %f','total deposit : %d','contraction A : %d','contraction B : %d', corr, cc, deposit, cont_A, cont_B);
annotation(figure1,'textbox',...
    [0.132379248658318 0.136363636363636 0.756708407871198 0.10064068824544],...
    'String',tmp_str,...
    'FontSize',10,...
    'FontAngle','italic',...
    'FitBoxToText','off',...
    'LineStyle','none');

    % [0.143011910135768 0.661388268070604 0.744501545192542 0.208550573514077],...
    
std_resid = std(Y1);

Y1_max = max(abs(Y1));
y_max = max(3*std_resid, Y1_max)*1.1;

X1_size = size(X1);
xlim([X1(1) X1(X1_size(1))]);
ylim([-y_max y_max]);

datetick('x', 6);

hline = refline([0 0]);
set(hline, 'LineWidth',1.5,'LineStyle',':', 'Color', 'k');

hline = refline([0 0.5*std_resid]);
set(hline, 'LineWidth',1.5,'LineStyle',':', 'Color', 'r');
hline = refline([0 -0.5*std_resid]);
set(hline, 'LineWidth',1.5,'LineStyle',':', 'Color', 'r');

hline = refline([0 1.96*std_resid]);
set(hline, 'LineWidth',1.5,'LineStyle',':', 'Color', 'g');
hline = refline([0 -1.96*std_resid]);
set(hline, 'LineWidth',1.5,'LineStyle',':', 'Color', 'g');

hline = refline([0 3*std_resid]);
set(hline, 'LineWidth',1.5,'LineStyle',':', 'Color', 'b');
hline = refline([0 -3*std_resid]);
set(hline, 'LineWidth',1.5,'LineStyle',':', 'Color', 'b');


